version: "3"
services:
  postgres:
    image: postgres:16-alpine
    container_name: bankservice-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./api/schema:/docker-entrypoint-initdb.d
    networks:
      - default

  bankservice-api:
    image: acmesky-bankservice-api
    container_name: bankservice-api
    networks:
      - default
      - acmesky
    environment:
      - DATABASE_DSN=${DATABASE_DSN}
      - API_TOKEN=${API_TOKEN}
    depends_on:
      - postgres
    ports:
      - "9280:8080"
    restart: unless-stopped

  bankservice-ui:
    image: acmesky-bankservice-ui
    container_name: bankservice-ui
    networks:
      - acmesky
    ports:
      - "9281:80"

volumes:
  postgres-data:
  acmesky:
    external: true
