info:
  title: ACMEacmebank API
  description: |-
    This is the description for the API used by ACMESky for acmebank management.
  version: 1.0.0
paths:
  /v1/payments/:
    post:
      consumes:
      - application/json
      description: Create a new payment
      produces:
      - application/json
      responses:
        "201":
          description: Created
      summary: Create a new payment
      tags:
      - Payments
  /v1/payments/{paymentId}/:
    get:
      consumes:
      - application/json
      description: Get an payment
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Get an payment
      tags:
      - Payments
    put:
      consumes:
      - application/json
      description: Pay a payment
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Pay a payment
      tags:
      - Payments
swagger: "2.0"
