version: '3'
services:
  postgres:
    image: postgres:16-alpine
    container_name: bankservice-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  bankservice-api:
    image: acmesky-bankservice-api
    container_name: bankservice-api
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data:
